### ISSUE TITLE
Possible error in readme for CYTFM_064B0S2_4343W related to user app keys

### ISSUE THREAD

**Issue by maclobdell** [PelionIoT/mbed-os-example-pelion-psoc64#2]
**Describe the bug**
In the readme file at https://github.com/ARMmbed/mbed-os-example-pelion-armdevsummit/blob/armdevsummit/TARGET_CYTFM_064B0S2_4343W/README.md

In Section: 
**Generating and provisioning Device Management credentials**

Step 5

I don't think these steps are needed. Or at least the step about creating keys is not needed. Because the next step uses 'existing keys'. Therefore the second set of keys are not really used. I think the readme is also wrong in this case. The first keys are important, and should not be deleted. The second keys are not necessary.  

We need to confirm this and fix the readme as soon as possible.

**Comment by moshe-shahar** [comment]
Cypress's suggestion was to provisioning inside mbed-os directory but since I couldn't run this step multiple times, I couldn't test additional flows so I separated the provisioning and re-provisioning steps completely.
Also, each step is using a different policy file that can create a different set of keys.

**Comment by maclobdell** [comment]
okay, I will walk through the flow and double check my understanding, then close this ticket.

**Comment by maclobdell** [comment]
it is working. we can keep it how it is.
